use_frameworks!
platform :ios, '9.0'

target 'DlOemMoudle_Example' do
    
  pod 'DlOemMoudle', :path => '../'
#  pod 'FSCalendar'
#  pod 'SwiftDate'
#  pod 'RxSwift'
#  pod 'RxCocoa'
#  pod 'R.swift'
#  pod 'RealmSwift'
#
#  pod 'CocoaLumberjack'

  target 'DlOemMoudle_Tests' do
    inherit! :search_paths

    
  end
end
