use_frameworks!
platform :ios, '9.0'
#source 'https://github.com/ModulizationDemo/PrivatePods.git'

target 'DlOemMoudle_Example' do
    
  pod 'DlOemMoudle', :path => '../'
  pod 'BeeHive'
#  pod 'FSCalendar'
#  pod 'SwiftDate'
#  pod 'RxSwift'
#  pod 'RxCocoa'
#  pod 'R.swift'
#  pod 'RealmSwift'
#
#  pod 'CocoaLumberjack'
end
